// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOl-gzs6ZNhwkwhXCyzMrdh46Rp744Guw',
    appId: '1:413524511570:web:0573d081d16e72a43ec88b',
    messagingSenderId: '413524511570',
    projectId: 'parkingapp-f01ff',
    authDomain: 'parkingapp-f01ff.firebaseapp.com',
    storageBucket: 'parkingapp-f01ff.firebasestorage.app',
    measurementId: 'G-16Z1GHCNRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqouvWP-OZsKFaysYXny4eSthTaSXDfm0',
    appId: '1:413524511570:android:07cefe1037194bd63ec88b',
    messagingSenderId: '413524511570',
    projectId: 'parkingapp-f01ff',
    storageBucket: 'parkingapp-f01ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1MCfrzTYwX3vDoT8qE0P2l5yOqF5JtA4',
    appId: '1:413524511570:ios:b7dd81ab37b7f1563ec88b',
    messagingSenderId: '413524511570',
    projectId: 'parkingapp-f01ff',
    storageBucket: 'parkingapp-f01ff.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1MCfrzTYwX3vDoT8qE0P2l5yOqF5JtA4',
    appId: '1:413524511570:ios:b7dd81ab37b7f1563ec88b',
    messagingSenderId: '413524511570',
    projectId: 'parkingapp-f01ff',
    storageBucket: 'parkingapp-f01ff.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOl-gzs6ZNhwkwhXCyzMrdh46Rp744Guw',
    appId: '1:413524511570:web:225ce64cf90bb2243ec88b',
    messagingSenderId: '413524511570',
    projectId: 'parkingapp-f01ff',
    authDomain: 'parkingapp-f01ff.firebaseapp.com',
    storageBucket: 'parkingapp-f01ff.firebasestorage.app',
    measurementId: 'G-2RWPYTTQ23',
  );
}
